### ISSUE TITLE
Upgrade was completed with issues

### ISSUE THREAD

**Issue by okamara** [zebrunner/zebrunner#361]
Steps:
setup zebrunner from master (1.2v)
do basic acceptance
-> take a look to ./jenkins/variables.env - no ZEBRUNNER_PIPELINE variable declared inside
switch to develop and pull latest changes recursively
run ./zebrunner.sh upgrade steps and restart everything
Actual result: Upgrade was completed with issues
patch/1.3.sh: line 30: local: can only be used in a function
<img width="575" alt="Screen Shot 2020-11-24 at 3 33 34 PM" src="https://user-images.githubusercontent.com/32964663/100095561-bcde5d80-2e6b-11eb-91f5-1bd3d1486b7a.png">

Actual result:  ./jenkins/variables.env - ZEBRUNNER_PIPELINE=1.3 is not declared

**Comment by vdelendik** [comment]
fixed. "local' var declaration is not used anymore in 1.3.sh patch script

**Comment by okamara** [comment]
Issue is not fixed 100%
Steps:
setup zebrunner from master (1.2v)
do basic acceptance
-> take a look to ./jenkins/variables.env - no ZEBRUNNER_PIPELINE variable declared inside
switch to develop and pull latest changes recursively
run ./zebrunner.sh upgrade steps and restart everything
Open ./jenkins/variables.env and verify  ZEBRUNNER_PIPELINE=1.3 is declared
Actual result: ./jenkins/variables.env - ZEBRUNNER_PIPELINE=1.3 is not declared

**Comment by okamara** [comment]
Upgrade was completed after run the following commands:
git checkout develop
git pull --recurse-submodules
./zebrunner.sh upgrade
